
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.border.Border;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author skjun
 */
public class Play_Frame extends javax.swing.JFrame {
    
    
    Border gray_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.DARK_GRAY);
    Border orange_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.ORANGE);
    
    
    String paper = "/images/paper.png";
    String scissors = "/images/scissors.png";
    /**
     * Creates new form Play_Frame
     */
    public Play_Frame() {
        initComponents();
        
        jLabel_You.setBorder(gray_border);
        jLabel_Computer.setBorder(gray_border);
        jLabel_Rock_.setBorder(gray_border);
        jLabel_Paper_.setBorder(gray_border);
        jLabel_Scissors_.setBorder(gray_border);
        
        displayImage(rock,jLabel_Rock_);
        displayImage(rock,jLabel_Paper_);
        displayImage(rock,jLabel_Scissors_);
    }
    
    
    
    public void displayImage(String imagePath,JLabel label)
    {
        ImageIcon imgIco = new ImageIcon(getClass().getResource("/images/rock.png"));
        
        Image img = imgIco.getImage().getScaledInstance(label.getWidth(), label.getHeight(),Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Computer = new javax.swing.JLabel();
        jLabel_Paper_ = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_YourWins = new javax.swing.JLabel();
        jLabel_ComputerWins = new javax.swing.JLabel();
        jLabel_You = new javax.swing.JLabel();
        jLabel_Rock_ = new javax.swing.JLabel();
        jLabel_Scissors_ = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));

        jLabel_Computer.setBackground(new java.awt.Color(255, 204, 204));
        jLabel_Computer.setOpaque(true);

        jLabel_Paper_.setBackground(new java.awt.Color(255, 204, 204));
        jLabel_Paper_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Paper_.setOpaque(true);
        jLabel_Paper_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Paper_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Paper_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Paper_MouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("-");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel_YourWins.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel_YourWins.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_YourWins.setText("0");
        jLabel_YourWins.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel_ComputerWins.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel_ComputerWins.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ComputerWins.setText("0");
        jLabel_ComputerWins.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel_You.setBackground(new java.awt.Color(255, 204, 204));
        jLabel_You.setOpaque(true);

        jLabel_Rock_.setBackground(new java.awt.Color(255, 204, 204));
        jLabel_Rock_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Rock_.setOpaque(true);
        jLabel_Rock_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Rock_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Rock_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Rock_MouseExited(evt);
            }
        });

        jLabel_Scissors_.setBackground(new java.awt.Color(255, 204, 204));
        jLabel_Scissors_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Scissors_.setOpaque(true);
        jLabel_Scissors_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Scissors_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Scissors_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Scissors_MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("YOU");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("COMPUTER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Rock_, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel_Paper_, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel_Scissors_, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_YourWins, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_ComputerWins, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_Computer, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(73, 73, 73))))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(jLabel_You, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(389, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel_Computer, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_YourWins, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ComputerWins, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Rock_, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(jLabel_Paper_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Scissors_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jLabel_You, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(240, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_Rock_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Rock_MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Rock_MouseClicked

    private void jLabel_Paper_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Paper_MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Paper_MouseClicked

    private void jLabel_Scissors_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Scissors_MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Scissors_MouseClicked

    private void jLabel_Rock_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Rock_MouseEntered
        jLabel_Rock_.setBorder(orange_border);   
    }//GEN-LAST:event_jLabel_Rock_MouseEntered

    private void jLabel_Rock_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Rock_MouseExited
        jLabel_Rock_.setBorder(gray_border);
    }//GEN-LAST:event_jLabel_Rock_MouseExited

    private void jLabel_Paper_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Paper_MouseEntered
        jLabel_Rock_.setBorder(orange_border);
    }//GEN-LAST:event_jLabel_Paper_MouseEntered

    private void jLabel_Paper_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Paper_MouseExited
        jLabel_Rock_.setBorder(gray_border);
    }//GEN-LAST:event_jLabel_Paper_MouseExited

    private void jLabel_Scissors_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Scissors_MouseEntered
        jLabel_Rock_.setBorder(orange_border);
    }//GEN-LAST:event_jLabel_Scissors_MouseEntered

    private void jLabel_Scissors_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Scissors_MouseExited
        jLabel_Rock_.setBorder(gray_border);
    }//GEN-LAST:event_jLabel_Scissors_MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Play_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Computer;
    private javax.swing.JLabel jLabel_ComputerWins;
    private javax.swing.JLabel jLabel_Paper_;
    private javax.swing.JLabel jLabel_Rock_;
    private javax.swing.JLabel jLabel_Scissors_;
    private javax.swing.JLabel jLabel_You;
    private javax.swing.JLabel jLabel_YourWins;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
